# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conversor_de_pdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1067, 810)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 40, 1001, 701))
        self.widget.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.widget.setObjectName("widget")
        self.lbl_conversor = QtWidgets.QLabel(self.widget)
        self.lbl_conversor.setGeometry(QtCore.QRect(280, 150, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_conversor.setFont(font)
        self.lbl_conversor.setStyleSheet("color: rgb(0, 0, 127);")
        self.lbl_conversor.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_conversor.setObjectName("lbl_conversor")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(50, 280, 881, 55))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.widget1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.pdf = self.lineEdit.text()
        self.format = self.comboBox.currentText()
        
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_conversor.setText(_translate("Dialog", "Conversor de PDFs"))
        self.label.setText(_translate("Dialog", "Arquivo em PDF:"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Digite aqui o path do arquivo"))
        self.comboBox.setItemText(0, _translate("Dialog", "Formato"))
        self.comboBox.setItemText(1, _translate("Dialog", "XLS"))
        self.comboBox.setItemText(2, _translate("Dialog", "XLSX"))
        self.comboBox.setItemText(3, _translate("Dialog", "CSV"))
        self.comboBox.setItemText(4, _translate("Dialog", "DOC"))
        self.comboBox.setItemText(5, _translate("Dialog", "DOCX"))
        self.pushButton.setText(_translate("Dialog", "Convert"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
    
    
    
"""
import pandas as pd

pdf_01 = '/run/media/erik_proenca/Elements/projetos/Nubank_2023-05-11.pdf'
pdf_02 = '/run/media/erik_proenca/Elements/projetos/Nubank_2023-06-11.pdf'

csv_01 = '/run/media/erik_proenca/Elements/projetos/Nubank_2023-05-11.xlsx'
csv_02 = '/run/media/erik_proenca/Elements/projetos/Nubank_2023-06-11.xlsx'

tb.convert_into(pdf_01, csv_01, output_format='csv', pages='all')
tb.convert_into(pdf_02, csv_02, output_format='csv', pages='all')

df_01 = pd.read_csv(csv_01)
df_02 = pd.read_csv(csv_02)
df_01.to_excel('Nubank_2023-05-11.xlsx', index=False)
df_02.to_excel('Nubank_2023-06-11.xlsx', index=False)
"""
